-- CREATE TABLE users
-- (
--     id         uuid PRIMARY KEY,
--     created_at timestamptz         NOT NULL,
--     updated_at timestamptz,
--     username   varchar(50) UNIQUE  NOT NULL,
--     email      varchar(100) UNIQUE NOT NULL,
--     password   varchar(60)         NOT NULL,
--     profile_id uuid
-- );
--
-- -- BinaryContent
-- CREATE TABLE binary_contents
-- (
--     id           uuid PRIMARY KEY,
--     created_at   timestamptz  NOT NULL,
--     file_name    varchar(255) NOT NULL,
--     size         bigint       NOT NULL,
--     content_type varchar(100) NOT NULL
-- --     ,bytes        bytea        NOT NULL
-- );
--
-- -- 제약 조건
-- -- User (1) -> BinaryContent (1)
-- ALTER TABLE users
--     ADD CONSTRAINT fk_user_binary_content
--         FOREIGN KEY (profile_id)
--             REFERENCES binary_contents (id)
--             ON DELETE SET NULL;
--
-- CREATE TABLE user_statuses
-- (
--     id             uuid PRIMARY KEY,
--     created_at     timestamptz NOT NULL,
--     updated_at     timestamptz,
--     user_id        uuid UNIQUE NOT NULL,
--     last_active_at timestamptz NOT NULL
-- );
--
-- -- UserStatus (1) -> User (1)
-- ALTER TABLE user_statuses
--     ADD CONSTRAINT fk_user_status_user
--         FOREIGN KEY (user_id)
--             REFERENCES users (id)
--             ON DELETE CASCADE;
--
--
-- -- 1) channels
-- CREATE TABLE IF NOT EXISTS channels (
--                                         id          UUID PRIMARY KEY,
--                                         created_at  TIMESTAMPTZ NOT NULL,
--                                         updated_at  TIMESTAMPTZ,
--                                         name        VARCHAR(100),
--     description VARCHAR(500),
--     type        VARCHAR(10) NOT NULL
--     );
--
-- -- ERD상 type은 PUBLIC / PRIVATE
-- ALTER TABLE channels
-- DROP CONSTRAINT IF EXISTS ck_channels_type;
--
-- ALTER TABLE channels
--     ADD CONSTRAINT ck_channels_type
--         CHECK (type IN ('PUBLIC', 'PRIVATE'));
--
-- -- 2) read_statuses
-- CREATE TABLE IF NOT EXISTS read_statuses (
--                                              id           UUID PRIMARY KEY,
--                                              created_at   TIMESTAMPTZ NOT NULL,
--                                              updated_at   TIMESTAMPTZ,
--                                              user_id      UUID NOT NULL,
--                                              channel_id   UUID NOT NULL,
--                                              last_read_at TIMESTAMPTZ NOT NULL
-- );
--
-- -- 복합 유니크 제약: 같은 user/channel 조합은 1개만
-- ALTER TABLE read_statuses
-- DROP CONSTRAINT IF EXISTS uk_read_status_user_channel;
--
-- ALTER TABLE read_statuses
--     ADD CONSTRAINT uk_read_status_user_channel
--         UNIQUE (user_id, channel_id);
--
-- -- FK
-- ALTER TABLE read_statuses
-- DROP CONSTRAINT IF EXISTS fk_read_status_user;
--
-- ALTER TABLE read_statuses
--     ADD CONSTRAINT fk_read_status_user
--         FOREIGN KEY (user_id)
--             REFERENCES users (id)
--             ON DELETE CASCADE;
--
-- ALTER TABLE read_statuses
-- DROP CONSTRAINT IF EXISTS fk_read_status_channel;
--
-- ALTER TABLE read_statuses
--     ADD CONSTRAINT fk_read_status_channel
--         FOREIGN KEY (channel_id)
--             REFERENCES channels (id)
--             ON DELETE CASCADE;
--
-- -- 3) messages
-- CREATE TABLE IF NOT EXISTS messages (
--                                         id          UUID PRIMARY KEY,
--                                         created_at  TIMESTAMPTZ NOT NULL,
--                                         updated_at  TIMESTAMPTZ,
--                                         content     TEXT NOT NULL,
--                                         channel_id  UUID NOT NULL,
--                                         author_id   UUID
-- );
--
-- -- FK
-- ALTER TABLE messages
-- DROP CONSTRAINT IF EXISTS fk_message_channel;
--
-- ALTER TABLE messages
--     ADD CONSTRAINT fk_message_channel
--         FOREIGN KEY (channel_id)
--             REFERENCES channels (id)
--             ON DELETE CASCADE;
--
-- ALTER TABLE messages
-- DROP CONSTRAINT IF EXISTS fk_message_author;
--
-- ALTER TABLE messages
--     ADD CONSTRAINT fk_message_author
--         FOREIGN KEY (author_id)
--             REFERENCES users (id)
--             ON DELETE SET NULL;
--
-- -- 4) message_attachments
-- CREATE TABLE IF NOT EXISTS message_attachments (
--                                                    message_id    UUID NOT NULL,
--                                                    attachment_id UUID NOT NULL,
--                                                    PRIMARY KEY (message_id, attachment_id)
--     );
--
-- ALTER TABLE message_attachments
-- DROP CONSTRAINT IF EXISTS fk_message_attachment_message;
--
-- ALTER TABLE message_attachments
--     ADD CONSTRAINT fk_message_attachment_message
--         FOREIGN KEY (message_id)
--             REFERENCES messages (id)
--             ON DELETE CASCADE;
--
-- ALTER TABLE message_attachments
-- DROP CONSTRAINT IF EXISTS fk_message_attachment_binary_content;
--
-- ALTER TABLE message_attachments
--     ADD CONSTRAINT fk_message_attachment_binary_content
--         FOREIGN KEY (attachment_id)
--             REFERENCES binary_contents (id)
--             ON DELETE CASCADE;
